<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: sans-serif; font-size: 11px; color: #1a1a1a; }
    h1 { font-size: 16px; margin-bottom: 4px; }
    .meta { color: #555; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid #ccc; padding: 4px 6px; text-align: left; }
    th { background-color: #f0f0f0; }
    tr:nth-child(even) td { background-color: #fafafa; }
</style>
</head>
<body>
    <h1>{{ $dataset->title }}</h1>
    <p class="meta">
        Generated by {{ auth()->user()?->name ?? 'system' }} on {{ now()->format('Y-m-d H:i') }}
    </p>

    <table>
        <thead>
            <tr>
                @foreach ($dataset->columns as $label)
                    <th>{{ $label }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($dataset->rows as $row)
                <tr>
                    @foreach ($dataset->columns as $key => $label)
                        <td>{{ $row[$key] ?? '' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($dataset->columns) }}">No data matched the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
